#!/usr/bin/env python3
# -*- coding: utf-8 -*-

class Student(object):
    def __init__(self, name, gender):
        self.__name = name
        self.__gender = gender

    def get_gender(self):
        return self.__gender

    def set_gender(self, gender):
##        self.__gender = gender
        if gender in ['male', 'female']:
            self.__gender = gender
        else:
            raise ValueError('invalid gender')
    


#test
bart = Student('Bart', 'male')
bart.set_gender('female')
print('bart.set_gender() =', bart.get_gender())
if bart.get_gender() not in ['female', 'male']:
    print('fail')
else:
    print('pass')
